title: 'Gonzalo Manuel Agüero'
shortTitle: 'Gonzalo M. Agüero'
baseURL: 'https://gonzalo-aguero.netlify.app/'
languageCode: es-AR
DefaultContentLanguage: es
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
paginate: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true
scripts:
  # - assets/js/scroll.js
  # - assets/js/scrollreveal.js
  # - assets/js/scrollreveal-config

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

params:
  author: Gonzalo Agüero
  authorimage: ../assets/images/global/author.webp
  og_image: /images/tailbliss-cover.png
  moto: "Desarrollador de Software"
  description: "Programador desde hace más de dos años y actualmente estudiante de Ingeniería en Sistemas en la UTN de Santa Fe, Argentina."
  disable_theme_toggle: false
  disable_stay_uptodate: false

  p1:
    active: true
    heading: "Sobre mí"
    image: "images/pages/our-mission.png"
    showImage: false
    content:
      - text: "Mi nombre es Gonzalo Manuel Agüero y soy desarrollador de software. Aunque actualmente estoy en las etapas iniciales de mi carrera, he adquirido experiencia realizando varios proyectos, tanto personales como para clientes."
      - text: "Por el momento, mi enfoque principal es el desarrollo web. Sin embargo, también tengo un poco de experiencia en desarrollo de aplicaciones móviles con React Native y Expo, así como en desarrollo de aplicaciones de escritorio con Java."
      
  p2:
    active: true
    heading: "Educación y aprendizaje"#"Formación y desarrollo"
    image: "images/pages/hacktoberfest.jpg"
    showImage: false
    content:
      - text: "Actualmente soy estudiante de tercer año de Ingeniería en Sistemas en la Universidad Tecnológica Nacional (UTN) de Santa Fe, Argentina."
      - text: "Mi pasión por el desarrollo software me impulsa a aprender continuamente y a esforzarme por mejorar tanto mis habilidades como la calidad de mis proyectos. Disfruto adquiriendo nuevos conocimientos y aplicando buenas prácticas para incrementar la eficiencia y calidad en mis desarrollos."
      - text: "Durante mis viajes, me gusta mantenerme actualizado sobre las últimas tendencias y novedades del sector leyendo diferentes artículos en daily.dev. Además, para mejorar mi capacidad de análisis y resolución de problemas, disfruto resolviendo ejercicios de programación en plataformas como LeetCode."
  p3:
    heading: "Tecnologías"
    content:
      - text: "He adquirido y aplicado mis conocimientos en varios proyectos utilizando principalmente JavaScript y PHP, tanto en su versión vanilla como con el framework Laravel. Para la estética de los sitios web, manejo tanto CSS3 como TailwindCSS."
      - text: "Durante mis estudios en la universidad, aprendí a utilizar SQL, con un enfoque principal en PostgreSQL."
      - text: "En cuanto a React, lo he aprendido e implementado en el desarrollo de una aplicación personal para la gestión de gastos."
      - text: "Actualmente, uso Linux como mi sistema operativo principal. Me siento muy cómodo utilizando la terminal y estoy familiarizado con la estructura de archivos, los comandos más comunes, y gracias a mi formación académica, tengo un sólido entendimiento de los sistemas operativos. Esto me permite investigar y resolver problemas con mayor facilidad cuando sea necesario."
    # links:
    #   - text: Meet our investors and advisors
    #     url: "#"
    logos:
      - identifier: a
        image: "images/icons/javascript-original.svg"
        title: "JavaScript"
        alt: "JavaScrit"
      - identifier: b
        image: "images/icons/php-original.svg"
        title: "PHP"
        alt: "PHP"
      - identifier: b
        image: "images/icons/laravel-original.svg"
        title: "Laravel"
        alt: "Laravel"
      - identifier: b
        image: "images/icons/react-original-wordmark.svg"
        title: "React JS"
        alt: "React JS"
      - identifier:  b
        image: "images/icons/postgresql-original-wordmark.svg"
        title: "PostgreSQL"
        alt: "PostgreSQL"
      - identifier: b
        image: "images/icons/linux-original.svg"
        title: "Linux"
        alt: "Linux"
      - identifier: b
        image: "images/icons/tailwindcss-original.svg"
        title: "Tailwind CSS"
        alt: "Tailwind CSS"
      - identifier: b
        image: "images/icons/html5-original-wordmark.svg"
        title: "HTML5"
        alt: "HTML5"
      - identifier: b
        image: "images/icons/css3-original-wordmark.svg"
        title: "CSS3"
        alt: "CSS3"
  p4:
    heading: "Proyectos"
    content:
      - text: "Los siguientes son los proyectos en los que he trabajado"
  p5:
    heading: "Conecta conmigo"
    email: "gonzaloaguerodev@gmail.com"
    content:
      - text: ""
    action: "#"
    label: "Email address"
    placeholder: "Enter your email"
    button: "Notify me"

  social_media:
    github:
      enabled: true
      url: 'https://github.com/gonzalo-aguero'
    linkedin:
      enabled: true
      url: 'https://www.linkedin.com/in/gonzalo-aguero/'
    email:
      enabled: true
      url: 'mailto:gonzaloaguerodev@gmail.com'
    facebook:
      enabled: false
      url: 'https://facebook.com/'
    instagram:
      enabled: false
      url: 'https://instagram.com/nusserstudios'
    twitter:
      enabled: false
      url: 'https://twitter.com/nusserstudios'
    

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: Sobre mí
      url: "#about"
      weight: 20
    - identifier: projects
      name: Proyectos
      url: "#projects"
      weight: 30
    - identifier: contact
      name: Contacto
      url: "#contact"
      weight: 50
  footer:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: blog
      name: Blog
      url: /categories/blog/
      weight: 20
    - identifier: news
      name: News
      url: /categories/news/
      weight: 30
    - identifier: prose
      name: Prose
      url: /prose/
      weight: 40
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: Categories
  tag: Tags

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

module:
  hugoVersion:
    extended: true
    min: "0.104.0"